#
# URL settings
#
# these need to be adjusted depending on target platform,

# "real" deployment with github-pages but custom domain
# -----------------------------------------------------
url: https://quality.arc42.org
imageurl: https://quality.arc42.org
baseurl:

#######################################################



#
# basic settings
#
title: arc42 Quality Model
description: quality attributes, explained.
avatar: /assets/img/arc42logosquare.webp
favicon: /assets/img/arc42logosquare.webp
language: en

#
# want subtle ads (on post-pages)
#
show-subtle-ads: false


#
# Icons and Social-Media accounts
#
icons:
  rss: false
  email: 
  github: arc42
  twitter: gernotstarke
  youtube: arc42-video
  stack_overflow: arc42
  dev_to: gernotstarke

#
# Prettify url.
#
permalink: pretty


#
# Localizations.
#
str_next: Next
str_prev: Prev
str_read_more: Read more...
str_search: Search
str_recent_posts: Recent answers
str_show_all_posts: Show all...

#
# Gems.
#
plugins:
  - jekyll-paginate
  - jemoji

#
# tags, collections etc -
# see https://jekyllrb.com/docs/collections/

# this DOES NOT WORK with tags!
collections:
  articles:
    output: true
    hide: true
  examples:
    output: true
    hide: true    


#
# with this default, all files under /_posts (a collection did not work with tags)
# get the qualities-layout per default, saving a bit of typing
#
defaults:
  -
    scope:
      path: ""
      type: "posts" # a collection in your site, in plural form
    values:
      layout: "qualities"  
#
# Styles: see "_sass/base/_variables.scss"
#

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


#
# !! Danger zone !!
#

include: ["_pages"]

markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

excerpt_separator: <!--more-->

sass:
  sass_dir: _sass
  style: :compressed # or :expanded

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - Dockerfile
  - .code-workspace
  - README.md
  - .vscode
  - originals/*
  - _docker-compose*
  - _manage*
  - .sass-cache

