# docker-compose definition for developing the site.
#
version: '2'

services:
  faq-arc42-jekyll:
    build: .
    image: doc-arc42-site:latest
    command: jekyll serve --trace --host 0.0.0.0 --watch --incremental --config _config.yml
    environment:
      - JEKYLL_ENV=development
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
